hausa_dictionary = {
    "Na": "Me",
    "Kana": "You",
    "Shi/Ita": "He/She",
    "Mun": "We",
    "Kun": "You (plural)",
    "Su": "They",
    "Baba": "Father",
    "Mama": "Mother",
    "Yaro": "Boy",
    "Yarinya": "Girl",
    "Uba": "Husband",
    "Mata": "Wife",
    "Gida": "House",
    "Motar": "Car",
    "Okirika": "Bicycle",
    "Sallah": "Festival",
    "Makaranta": "School",
    "Malam": "Teacher",
    "Alhaji": "Hajj",
    "Alhaja": "Hajjah",
    "Kowa": "Everyone",
    "Wane": "Here",
    "Can": "There",
    "Yanzu": "Now",
    "Jiya": "Yesterday",
    "Gobe": "Tomorrow",
    "Rana": "Day",
    "Dare": "Night",
    "Ruwa": "Water",
    "zo":"come"
}

