igala_dictionary = {
    "oma": "child",
    "eje": "water",
    "ojo": "day",
    "ona": "road",
    "unyi": "house",
    "acho": "want",
    "olu": "work",
    "efu": "clothes",
    "ata": "father",
    "ene": "mother",
    "abo": "hand",
    "ekpe": "firewood",
    "ekwo": "goat",
    "amaka": "beautiful",
    "ola": "tomorrow",
    "oje": "food",
    "onu": "mouth",
    "abu": "song",
    "ogba": "compound",
    "aji": "salt",
    "efu oma": "clothes for a child",
    "eje olo": "river",
    "ojoeme": "good day",
    "eche": "night",
    "ebi": "hunger",
    "omo": "life",
    "oko": "farm",
    "ekwu": "talk",
    "onyima": "friend",
}