mada_dictionary = {
    'gyer' : "one",
    'doglu' : "stand up",
    'tison' : "sit down",
    'susu' : "weldone",
    'nzeh' : "culture",
    'wheshen' : "good morning",
    'chun' : "king",
    'vellen' : "man",
    'mbe' : "woman",
    'lagema' : "helper",
    'tigbuchu' :"wow",
    'nyer' : "come",
    'wei' : "go",
    'khe' : "house",
    'kison' : "chair",
    'vwen' : "child",
    'kri' : "yam",
    'the' : "father",
    'vwen vulon' : "boy",
    'gyen' : "mother",
    'vwen vugen' : "girl",
    'mhesera' : "white skin",
    'hwon' : "farm",
    'meseir' : "water",
    'nwudu' : "trouser",
    'nwun' : "hand",
    'zeh' : "leg",
    'blah' : "read",
    'swei' : "bath",
    'ngi' : "cry",

}